language: java
jdk:
  - openjdk11
branches:
  only:
    - develop

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2./repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_deploy:
  - zip -r tumuto
  - mkdir -p deploy
  - mv tumuto.zip deploy/tumuto.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: tumuto-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로 설정
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deploy: true
    on:
      all_branches: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dajeongdev@gmail.com