server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cookiemonster.cdgpcvesaium.ap-northeast-2.rds.amazonaws.com:5432/cookiemonster
    username: cookiemonster
    password: cookie123!
  main:
    allow-bean-definition-overriding: true

oauth:
  kakao:
    client-id: 4aed26463538748deb5880a9d92033e3
    client-secret: 6tZFdhBks2utPB0NGuSRX1ygTcYiYkxZ
    redirect-uri: http://localhost:8080/user/oauth/kakao