spring:
  profiles:
    include: default

server:
  port: 8080
  error:
    include-stacktrace: always
    include-exception: true

logging:
  file:
    name: "/home/ubuntu/tumuto/log/tumuto.log"
    max-history: 31
  level:
    root: info

---

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cookiemonster.cdgpcvesaium.ap-northeast-2.rds.amazonaws.com:5432/cookiemonster
    username: cookiemonster
    password: cookie123!
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jpa:
    show_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 2edf4e7a1f9716a180ae8543a5c85bd6
            client-secret: 3mixsS23AFdfnA8BSqQbWiSpHlRyNLWV
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope: profile_nickname, profile_image
          naver:
            client-id: c4kTXMJtLugtxsn5a9ee
            client-secret: RoRGW7v7aZ
            redirect-uri: http://tumuto.kr/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  secret-key: cookiemonsterTumuto
  token-valid-time: 86400

cloud:
  aws:
    credentials:
      accessKey: AKIAVKRQNR6O3FSBLTG7
      secretKey: 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
    s3:
      bucket: tumuto-springboot-build
    region: ap-northeast-2
    stack:
      auto: false