spring:
  profiles:
    includes: real, oauth, real-db
  file-upload:
    base-dir: "/Users/hannah/cookieMonster/upload" # 지혜로컬 업로드경로
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jpa:
    show_sql: true
    format_sql: true

logging:
  level:
    root: info

---
spring:
  profiles: real
    include: oauth, real-db

server:
  port: 8090
---
spring:
  profiles: real1
    include: oauth, real-db

server:
  port: 8091
---
spring:
  profiles: real2
    include: oauth, real-db

server:
  port: 8092
---
spring:
  profiles: oauth

jwt:
  secret-key: cookiemonsterTumuto
  token-valid-time: 86400

oauth:
  kakao:
    client-id: 2edf4e7a1f9716a180ae8543a5c85bd6
    client-secret: 450105254230f617e0dce76ab870a95c
    redirect-uri: "http://localhost:8080/user/oauth/kakao"
  naver:
    client-id: c4kTXMJtLugtxsn5a9ee
    client-secret: RoRGW7v7aZ
    redirect-uri: "http://localhost:8080/user/oauth/naver"

---
spring:
  profiles: real-db

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cookiemonster.cdgpcvesaium.ap-northeast-2.rds.amazonaws.com:5432/cookiemonster
    username: cookiemonster
    password: cookie123!