name: Tumuto Backend CI

on:
  push: 
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  

jobs:
  build:
  
    # 실행 환경 지정
    runs-on: ubuntu-latest

    # job의 순서 명시
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    # Before install
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # Build
    - name: Build with Gradle
      run: ./gradlew clean build
    
    
