name: Tumuto Backend CI

on:
  push: 
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  

jobs:
  build:
  
    # 실행 환경 지정
    runs-on: ubuntu-latest

    # job의 순서 명시
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    # Before install
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # Build
    - name: Build with Gradle
      run: ./gradlew clean build
        
    # 전송할 파일을 담을 디렉토리 생성
    - name: Make directory for deliver
      run: mkdir deploy

    # Jar 파일 copy
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy/

    # appspec.yml copy
    - name: Copy appspec
      run: cp appspec.yml ./deploy/

    # 압축 파일 형태로 전달
    - name: Make zip file
      run: zip -r -qq -j ./cookie-back.zip ./deploy

    # S3 Bucket으로 copy
    - name: Deliver to AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        --acl private \
        ./cookie-back.zip s3://tumuto-springboot-build/

    # Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
        --application-name tumuto \
        --deployment-group-name tumuto-group \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=tumuto-springboot-build,bundleType=zip,key=cookie-back.zip \
        --region ap-northeast-2